ТЗ спринт 7
biteforceee/java-kanban pull request #2
Opened 2024-08-16 23:39 UTC by biteforceee

2024-08-17 15:25 UTC, YazykovMikhail requested changes

2024-08-17 15:25 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lagutov/schedule/manager/FileBackedTaskManager.java
> +            fileWriter.write("ID;TYPE;TITLE;STATUS;NOTE;EPIC" + '\n');
Вынеси хедеры в переменную в константу, обрати внимание

2024-08-17 15:25 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lagutov/schedule/manager/FileBackedTaskManager.java
> +        try (Writer fileWriter = new FileWriter(filePath.toFile(), StandardCharsets.UTF_8)) {
try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) { используй буферизацию для экономиии ресурсов

2024-08-17 15:25 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lagutov/schedule/manager/FileBackedTaskManager.java
> +            fileWriter.write("ID;TYPE;TITLE;STATUS;NOTE;EPIC" + '\n');
Так же обрати внимание что заголовки не капсом

2024-08-17 15:25 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lagutov/schedule/manager/FileBackedTaskManager.java
> +            }
Перевод строки лучше делать
				writer.newLine();
ведь у каждой операционной системе свой символ перевода строки

2024-08-17 15:25 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lagutov/schedule/manager/FileBackedTaskManager.java
> +    public void loadFromFile(File file) {
Не стоит использовать бизнес методы для восстановления данных, добавляй непосредсвенно в хранилище, ведь необходимо что бы восстанавливались и идентификаторы а не создавались заного
И так же стоит восстанавливать счетчик идентификатора, ведь после восстановления работы необходимо что бы счетчик продолжился
```
public static FileBackedTaskManager loadFromFile(File file) {
		final FileBackedTaskManager taskManager = new FileBackedTaskManager(file);
		try {
			final String csv = Files.readString(file.toPath());
			final String[] lines = csv.split(System.lineSeparator());
			int generatorId = 0;
			for (int i = 1; i < lines.length; i++) {
				String line = lines[i];
				if (line.isEmpty()) {
					break;
				}
				final Task task = CSVTaskFormat.taskFromString(line);
				final int id = task.getId();
				if (id > generatorId) {
					generatorId = id;
				}
				taskManager.addAnyTask(task);
			}
			for (Map.Entry<Integer, Subtask> e : taskManager.subtasks.entrySet()) {
				final Subtask subtask = e.getValue();
				final Epic epic = taskManager.epics.get(subtask.getEpicId());
				epic.addSubtaskId(subtask.getId());
			}
			taskManager.generatorId = generatorId;
		} catch (IOException e) {
			throw new ManagerSaveException("Can't read form file: " + file.getName(), e);
		}
		return taskManager;
	}
```

2024-08-17 15:25 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lagutov/schedule/manager/FileBackedTaskManager.java
> +                Task task = new Task(param[2], param[4]);
сделай конструктор для всех полей, что б не делать сет

2024-08-17 15:25 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lagutov/schedule/manager/FileBackedTaskManager.java
> +    public void loadFromFile(File file) {
protected void addAnyTask(Task task) {
		final int id = task.getId();
		switch (task.getType()) {
			case TASK:
				tasks.put(id, task);
				break;
			case SUBTASK:
				subtasks.put(id, (Subtask) task);
				break;
			case EPIC:
				epics.put(id, (Epic) task);
				break;
		}
	}
Вспомогательный метод

2024-08-17 15:25 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lagutov/schedule/manager/InMemoryTaskManager.java
сделай все поля в этом классе protected что бы был прямой доступ у наследника

2024-08-17 15:25 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lagutov/schedule/Main.java
Теперь класс
```
public class Managers {
	public static TaskManager getDefault() {

		return new FileBackedTaskManager(new File("resources/task.csv"));
	}

	public static HistoryManager getDefaultHistory() {
		return new InMemoryHistoryManager();
	}
}

```
будет выглядеть вот так

2024-08-17 15:25 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lagutov/schedule/Main.java
добавь папку и файл в корень проекта
resources/task.csv

2024-08-18 04:14 UTC, biteforceee commented on src/ru/yandex/javacource/lagutov/schedule/manager/FileBackedTaskManager.java
> +    public void loadFromFile(File file) {
а что такое CSVTaskFormat в методе loadFromFile?

2024-08-18 08:27 UTC, YazykovMikhail requested changes

2024-08-18 08:27 UTC, YazykovMikhail commented on src/ru/yandex/javacource/lagutov/schedule/manager/FileBackedTaskManager.java
> +    private static final String fileHeader = "id;type;title;status;note;epic";
Статические переменные обьявляются первыми в классе - по кодстайлу

2024-08-18 08:28 UTC, YazykovMikhail approved these changes

2024-10-31 22:31 UTC, merged